#!/bin/bash

setxkbmap -layout "us,ru" -option "grp:alt_shift_toggle"
sxhkd &
feh --bg-scale ~/.config/wlpr/000000.png
polybar &
picom --experimental-backends -b &
bspc config split_ratio		  	0.62
bspc config focus_follows_pointer 	true
bspc config pointer_modifier		mod1
bspc config automatic_scheme		spiral
bspc monitor -d				1 2 3 4 5
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config focus_follows_pointer true
bspc config window_gaps 15
bspc config border_width 2
bspc config top_padding 45
bspc config bottom_padding 2
bspc config left_padding 2
bspc config right_padding 2
bspc config normal_border_color   "#ea9ca0"
bspc config active_border_color   "#c0caf5"
bspc config focused_border_color  "#f76671"
bspc config presel_feedback_color "#50fa7b"


